# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token: str=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param access_token: The access_token of this InlineResponse2002.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            'access_token': str
        }

        self.attribute_map = {
            'access_token': 'access_token'
        }
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this InlineResponse2002.


        :return: The access_token of this InlineResponse2002.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this InlineResponse2002.


        :param access_token: The access_token of this InlineResponse2002.
        :type access_token: str
        """

        self._access_token = access_token
