# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_items import InlineResponse200Items  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, items: List[InlineResponse200Items]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param name: The name of this InlineResponse200.  # noqa: E501
        :type name: str
        :param items: The items of this InlineResponse200.  # noqa: E501
        :type items: List[InlineResponse200Items]
        """
        self.swagger_types = {
            'name': str,
            'items': List[InlineResponse200Items]
        }

        self.attribute_map = {
            'name': 'name',
            'items': 'items'
        }
        self._name = name
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse200.


        :return: The name of this InlineResponse200.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse200.


        :param name: The name of this InlineResponse200.
        :type name: str
        """

        self._name = name

    @property
    def items(self) -> List[InlineResponse200Items]:
        """Gets the items of this InlineResponse200.


        :return: The items of this InlineResponse200.
        :rtype: List[InlineResponse200Items]
        """
        return self._items

    @items.setter
    def items(self, items: List[InlineResponse200Items]):
        """Sets the items of this InlineResponse200.


        :param items: The items of this InlineResponse200.
        :type items: List[InlineResponse200Items]
        """

        self._items = items
