# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_items import InlineResponse200Items  # noqa: F401,E501
from swagger_server import util


class InlineResponse2011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[InlineResponse200Items]=None):  # noqa: E501
        """InlineResponse2011 - a model defined in Swagger

        :param items: The items of this InlineResponse2011.  # noqa: E501
        :type items: List[InlineResponse200Items]
        """
        self.swagger_types = {
            'items': List[InlineResponse200Items]
        }

        self.attribute_map = {
            'items': 'items'
        }
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1 of this InlineResponse2011.  # noqa: E501
        :rtype: InlineResponse2011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[InlineResponse200Items]:
        """Gets the items of this InlineResponse2011.


        :return: The items of this InlineResponse2011.
        :rtype: List[InlineResponse200Items]
        """
        return self._items

    @items.setter
    def items(self, items: List[InlineResponse200Items]):
        """Sets the items of this InlineResponse2011.


        :param items: The items of this InlineResponse2011.
        :type items: List[InlineResponse200Items]
        """

        self._items = items
